name: Email Step Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 23f2000851@ds.study.iitm.ac.in
        run: echo "Hello, world!"
